import type { BrowserStorageItem } from '#shared/schemas/browserStorage'

/** File / job names for the ZAP Selenium script that seeds browser state.
 * The script carries secret values, so it is written 0600 and removed after
 * the run (see `runZap`'s `secretFiles`). */
export const BROWSER_STORAGE_SCRIPT_FILE = 'browser-storage.js'
export const BROWSER_STORAGE_SCRIPT_NAME = 'sakuda-browser-storage'
export const BROWSER_STORAGE_SCRIPT_ENGINE = 'ECMAScript : Graal.js'

/**
 * Builds a ZAP "selenium" script (`browserLaunched` hook, Selenium add-on)
 * that logs the SPA in before the Ajax spider crawls. ZAP launches every
 * browser on its own `https://zap/zapCallBackUrl/...` page, and web storage
 * is origin-bound, so the script first navigates to the site's origin, then
 * sets each item, then reloads so the app boots with the state in place.
 * Values are passed to `executeScript` as arguments — never spliced into
 * JS source — so a value with quotes or newlines cannot break out.
 */
export function buildBrowserStorageScript(items: BrowserStorageItem[], origins: string[]): string {
  return `// Generated by sakuda: seeds browser storage / cookies before the Ajax spider crawls.
var ITEMS = ${JSON.stringify(items)};
var ORIGINS = ${JSON.stringify(origins)};

function browserLaunched(utils) {
  var wd = utils.getWebDriver();
  var url = String(utils.waitForURL(10000));
  for (var o = 0; o < ORIGINS.length; o++) {
    if (url.indexOf(ORIGINS[o]) !== 0) wd.get(ORIGINS[o] + '/');
    for (var i = 0; i < ITEMS.length; i++) {
      var item = ITEMS[i];
      if (item.kind === 'cookie') {
        wd.executeScript("document.cookie = arguments[0] + '=' + arguments[1] + '; path=/'", item.name, item.value);
      } else {
        wd.executeScript('window[arguments[0]].setItem(arguments[1], arguments[2])', item.kind, item.name, item.value);
      }
    }
    url = '';
  }
  wd.executeScript('location.reload()');
  print('[${BROWSER_STORAGE_SCRIPT_NAME}] seeded ' + ITEMS.length + ' item(s) on ' + utils.getBrowserId());
}
`
}
