import { z } from 'zod'

/** File / job names for the ZAP standalone script that probes SPA hash routes
 * for DOM XSS from a real headless browser. It carries no secrets, so it is
 * written to the (disposable, per-scan) work dir as an `extraFile`, the same
 * way discovery writes its site-tree dump script. */
export const DOM_XSS_PROBE_SCRIPT_FILE = 'dom-xss-probe.js'
export const DOM_XSS_PROBE_OUTPUT_FILE = 'dom-xss-probe.json'
export const DOM_XSS_PROBE_SCRIPT_NAME = 'sakuda-dom-xss-probe'
export const DOM_XSS_PROBE_SCRIPT_ENGINE = 'ECMAScript : Graal.js'

/** Browser id the Ajax spider / active scan use; the probe reuses it so it
 * runs the same one headless Firefox (see plan's `numberOfBrowsers: 1`). */
export const DOM_XSS_PROBE_BROWSER_ID = 'firefox-headless'

/** ZAP plugin id for the raised alerts. 40026 is ZAP's own "Cross Site
 * Scripting (DOM Based)" rule; reusing it groups our findings with ZAP's and
 * keeps the report/normalize pipeline unchanged. */
export const DOM_XSS_PROBE_PLUGIN_ID = 40026

/**
 * Payloads injected into each route's empty query value. Restricted to sinks
 * that fire from `innerHTML`/DOM assignment (an inserted `<script>` does not
 * execute), each writing the per-attempt token to `window[__CANARY__]` so
 * detection never depends on an `alert()` dialog (which blocks headless).
 * `__CANARY__`/`__TOKEN__` are substituted in the browser, never in Node.
 */
export const DOM_XSS_PROBE_PAYLOADS: readonly string[] = [
  `<img src=x onerror="window['__CANARY__']='__TOKEN__'">`,
  `<iframe src="javascript:window.top['__CANARY__']='__TOKEN__'"></iframe>`,
  `<svg onload="window['__CANARY__']='__TOKEN__'">`,
]

export interface DomXssProbeConfig {
  /** Absolute hash-route URLs (loopback already aliased), e.g.
   * `http://host.docker.internal:3000/#/search?q=`. */
  routes: string[]
  /** Front origin (aliased) the browser opens first — `getProxiedBrowser`
   * navigates there on creation, which also gets us off ZAP's
   * `https://zap/zapCallBackUrl/...` launch page onto the real origin. */
  origin: string
  /** Container-side path the script writes its `{probed,hits,truncated}`
   * summary to (see `zapPath`). */
  outputPath: string
  /** Wall-clock budget for the whole probe, in ms. The script turns it into a
   * deadline at its own start (`Date.now() + budgetMs`), since it runs in the
   * ZAP process, not here; on overrun it stops and records `truncated: true`. */
  budgetMs: number
  /** How long to wait after each navigation for the SPA to render + the sink
   * to fire before reading the canary. */
  settleMs: number
  payloads?: readonly string[]
  canary?: string
}

const DEFAULT_CANARY = '__sakudaDomXss__'

/**
 * Builds the ZAP standalone Graal.js script that, for each hash route, opens
 * a proxied headless Firefox, injects each payload into the route's empty
 * query value, and — if the sink fires — raises a HIGH ZAP alert (attached to
 * a `HistoryReference` so it lands in `report.json`). One browser, driven
 * serially; a wall-clock deadline caps the run and is reported as `truncated`.
 *
 * All route/payload data is embedded with `JSON.stringify`, so a route value
 * can never break out of the script source; payloads are substituted into the
 * DOM inside the browser, not into this file.
 */
export function buildDomXssProbeScript(cfg: DomXssProbeConfig): string {
  const payloads = cfg.payloads ?? DOM_XSS_PROBE_PAYLOADS
  const canary = cfg.canary ?? DEFAULT_CANARY
  return `// Generated by sakuda: probes SPA hash routes for DOM XSS in a headless browser.
var Control = Java.type('org.parosproxy.paros.control.Control');
var Model = Java.type('org.parosproxy.paros.model.Model');
var ExtensionSelenium = Java.type('org.zaproxy.zap.extension.selenium.ExtensionSelenium');
var ExtensionAlert = Java.type('org.zaproxy.zap.extension.alert.ExtensionAlert');
var Alert = Java.type('org.parosproxy.paros.core.scanner.Alert');
var HistoryReference = Java.type('org.parosproxy.paros.model.HistoryReference');
var HttpMessage = Java.type('org.parosproxy.paros.network.HttpMessage');
var URI = Java.type('org.apache.commons.httpclient.URI');
var Files = Java.type('java.nio.file.Files');
var Paths = Java.type('java.nio.file.Paths');
var StandardCharsets = Java.type('java.nio.charset.StandardCharsets');

var ROUTES = ${JSON.stringify(cfg.routes)};
var PAYLOADS = ${JSON.stringify(payloads)};
var CANARY = ${JSON.stringify(canary)};
var BUDGET_MS = ${JSON.stringify(cfg.budgetMs)};
var SETTLE_MS = ${JSON.stringify(cfg.settleMs)};
var DEADLINE = Date.now() + BUDGET_MS;
var OUTPUT = ${JSON.stringify(cfg.outputPath)};
var BROWSER_ID = ${JSON.stringify(DOM_XSS_PROBE_BROWSER_ID)};
var ORIGIN = ${JSON.stringify(cfg.origin)};
var PLUGIN_ID = ${JSON.stringify(DOM_XSS_PROBE_PLUGIN_ID)};
var NAME = ${JSON.stringify(DOM_XSS_PROBE_SCRIPT_NAME)};

function log(m) { print('[' + NAME + '] ' + m); }

// Inject the (already URL-encoded) payload into every empty query value in
// the fragment ("?q=" -> "?q=<enc>"); if there is none, append "&sakuda=<enc>".
function injectPayload(url, enc) {
  var hashIdx = url.indexOf('#');
  var head = hashIdx >= 0 ? url.substring(0, hashIdx) : url;
  var frag = hashIdx >= 0 ? url.substring(hashIdx) : '';
  var injected = frag.replace(/=(?=&|$)/g, '=' + enc);
  if (injected === frag) injected = frag + (frag.indexOf('?') >= 0 ? '&' : '?') + 'sakuda=' + enc;
  return head + injected;
}

function raiseAlert(routeUrl, payload) {
  var extAlert = Control.getSingleton().getExtensionLoader().getExtension(ExtensionAlert.class);
  var session = Model.getSingleton().getSession();
  var msg = new HttpMessage(new URI(routeUrl, true));
  msg.setResponseHeader('HTTP/1.1 200 OK\\r\\nContent-Type: text/html\\r\\n\\r\\n');
  var href = new HistoryReference(session, HistoryReference.TYPE_SCANNER, msg);
  var alert = Alert.builder()
    .setPluginId(PLUGIN_ID)
    .setName('Cross Site Scripting (DOM Based)')
    .setRisk(Alert.RISK_HIGH)
    .setConfidence(Alert.CONFIDENCE_HIGH)
    .setDescription('sakuda hash-route probe: a payload injected into the SPA hash route below executed in a headless browser (a DOM canary was set), confirming DOM-based XSS. The fragment never reaches the server, so ZAP\\'s spider and active scanner cannot reach this sink.')
    .setUri(routeUrl)
    .setParam('q')
    .setAttack(payload)
    .setEvidence(payload)
    .setSolution('Treat the URL fragment / query as untrusted in the SPA: render it as text, or sanitize before assigning to innerHTML / bypassing the framework escaping.')
    .setCweId(79)
    .setWascId(8)
    .setSource(Alert.Source.TOOL)
    .setMessage(msg)
    .build();
  extAlert.alertFound(alert, href);
  log('DOM XSS confirmed: ' + routeUrl);
}

var extSel = Control.getSingleton().getExtensionLoader().getExtension(ExtensionSelenium.class);
var wd = null;
var probed = 0;
var hits = 0;
var truncated = false;
try {
  // getProxiedBrowser(providedBrowserId, url) — the id is the same value the
  // Ajax spider job uses (e.g. "firefox-headless") and it navigates to that url
  // on creation, which also moves us off ZAP's zapCallBackUrl launch page.
  // (getProxiedBrowserByName takes a display name and returns null for an id.)
  // Inside the try so a bootstrap failure still writes the summary in finally.
  wd = extSel.getProxiedBrowser(BROWSER_ID, ORIGIN);
  for (var r = 0; r < ROUTES.length; r++) {
    if (Date.now() > DEADLINE) { truncated = true; break; }
    var route = ROUTES[r];
    for (var p = 0; p < PAYLOADS.length; p++) {
      if (Date.now() > DEADLINE) { truncated = true; break; }
      var token = 'sakuda' + Date.now() + '_' + r + '_' + p;
      var payload = PAYLOADS[p].replace(/__CANARY__/g, CANARY).replace(/__TOKEN__/g, token);
      var target = injectPayload(route, encodeURIComponent(payload));
      probed++;
      try {
        wd.get('about:blank');
        wd.get(target);
        java.lang.Thread.sleep(SETTLE_MS);
        var got = wd.executeScript('try { return window[arguments[0]]; } catch (e) { return null; }', CANARY);
        if (String(got) === token) {
          hits++;
          raiseAlert(route, PAYLOADS[p]);
          break; // one confirmation per route is enough
        }
      } catch (e) {
        log('probe error on ' + target + ': ' + e);
      }
    }
  }
} finally {
  if (wd !== null) { try { wd.quit(); } catch (e) { log('quit error: ' + e); } }
  Files.write(
    Paths.get(OUTPUT),
    JSON.stringify({ probed: probed, hits: hits, truncated: truncated }).getBytes(StandardCharsets.UTF_8),
  );
  log('done: probed=' + probed + ' hits=' + hits + ' truncated=' + truncated);
}
`
}

const Summary = z.object({
  probed: z.number().int(),
  hits: z.number().int(),
  truncated: z.boolean(),
})

export type DomXssProbeSummary = z.infer<typeof Summary>

/** Parses the `{probed,hits,truncated}` summary the script writes. Returns
 * null on missing/invalid output (treated as "no truncation known"). */
export function parseDomXssProbeSummary(text: string): DomXssProbeSummary | null {
  let json: unknown
  try {
    json = JSON.parse(text)
  } catch {
    return null
  }
  const r = Summary.safeParse(json)
  return r.success ? r.data : null
}
