import { z } from 'zod'
import type { DiscoveredUrl } from '#shared/types/api'
import { BodyShapeSchema, bodyShapeFunctionSource } from './bodyShape'

/** File names inside a discovery's work dir. The script is written by us
 * and run by ZAP's Automation Framework `script` job (scripts + Graal.js
 * add-ons, both bundled in the pinned ZAP image); it walks ZAP's site tree
 * — every URL the spiders requested — and dumps one JSON object per node. */
export const SITE_TREE_DUMP_SCRIPT_FILE = 'dump-site-tree.js'
export const SITE_TREE_DUMP_OUTPUT_FILE = 'site-tree.jsonl'
export const SITE_TREE_DUMP_SCRIPT_NAME = 'sakuda-dump-site-tree'
export const SITE_TREE_DUMP_ENGINE = 'ECMAScript : Graal.js'

/** `outputPath` is the path as seen by the ZAP process (container-side when
 * ZAP runs in Docker — see `zapPath`). */
export function buildSiteTreeDumpScript(outputPath: string): string {
  // `toBodyShape` is embedded verbatim (see bodyShape.ts) so the exact,
  // unit-tested shaping logic runs inside ZAP and only value-free shapes —
  // never raw request bodies — are written to the dump on disk.
  return `// Generated by sakuda: dumps ZAP's site tree as JSONL for discovery.
var Model = Java.type('org.parosproxy.paros.model.Model');
var Files = Java.type('java.nio.file.Files');
var Paths = Java.type('java.nio.file.Paths');
var StandardCharsets = Java.type('java.nio.charset.StandardCharsets');
${bodyShapeFunctionSource()}
var out = [];
function walk(node) {
  var ref = node.getHistoryReference();
  if (ref) {
    var method = String(ref.getMethod());
    var entry = {
      method: method,
      url: String(ref.getURI().toString()),
      type: ref.getHistoryType(),
      status: ref.getStatusCode()
    };
    // Only non-GET nodes can carry a body worth shaping. getHttpMessage() may
    // throw (I/O); on failure the shape is simply omitted — never a raw value
    // or an error message.
    if (method !== 'GET' && method !== 'HEAD') {
      try {
        var msg = ref.getHttpMessage();
        var body = String(msg.getRequestBody().toString());
        if (body.length > 0) {
          var ct = msg.getRequestHeader().getHeader('Content-Type');
          var ctStr = ct == null ? null : String(ct);
          var shape = toBodyShape(ctStr, body);
          if (shape !== null) {
            if (ctStr !== null) entry.contentType = ctStr;
            entry.bodyShape = shape;
          }
        }
      } catch (bodyErr) {
        // shape omitted
      }
    }
    out.push(JSON.stringify(entry));
  }
  for (var i = 0; i < node.getChildCount(); i++) walk(node.getChildAt(i));
}
walk(Model.getSingleton().getSession().getSiteTree().getRoot());
Files.write(Paths.get(${JSON.stringify(outputPath)}), out.join('\\n').getBytes(StandardCharsets.UTF_8));
print('sakuda dump-site-tree: ' + out.length + ' nodes');
`
}

const Entry = z.object({
  method: z.string(),
  url: z.string(),
  type: z.number().int(),
  status: z.number().int(),
  /** Present only for non-GET nodes whose request carried a body (see the dump
   * script). Old dumps without these fields still parse. */
  contentType: z.string().optional(),
  bodyShape: BodyShapeSchema.optional(),
})

export type SiteTreeEntry = z.infer<typeof Entry>

// org.parosproxy.paros.model.HistoryReference constants.
const HISTORY_TYPE_SPIDER = 2
const HISTORY_TYPE_SPIDER_AJAX = 10
const HISTORY_TYPE_SPIDER_CLIENT = 24

export function historyTypeToSource(type: number): DiscoveredUrl['source'] {
  if (type === HISTORY_TYPE_SPIDER) return 'spider'
  if (type === HISTORY_TYPE_SPIDER_AJAX) return 'ajax'
  if (type === HISTORY_TYPE_SPIDER_CLIENT) return 'client'
  return 'other'
}

/** Parses the JSONL dump. Structural nodes (folders ZAP synthesizes for a
 * path prefix, never actually requested) carry status 0 and are dropped
 * here — they are not URLs anything responded to. */
export function parseSiteTreeDump(text: string): {
  entries: SiteTreeEntry[]
  structuralCount: number
  invalidLines: number
} {
  const entries: SiteTreeEntry[] = []
  let structuralCount = 0
  let invalidLines = 0
  for (const line of text.split(/\r?\n/)) {
    if (line.trim() === '') continue
    let json: unknown
    try {
      json = JSON.parse(line)
    } catch {
      invalidLines++
      continue
    }
    const r = Entry.safeParse(json)
    if (!r.success) {
      invalidLines++
      continue
    }
    if (r.data.status === 0) {
      structuralCount++
      continue
    }
    entries.push(r.data)
  }
  return { entries, structuralCount, invalidLines }
}
