import { z } from 'zod'
import type { DiscoveredUrl } from '#shared/types/api'

/** File names inside a discovery's work dir. The script is written by us
 * and run by ZAP's Automation Framework `script` job (scripts + Graal.js
 * add-ons, both bundled in the pinned ZAP image); it walks ZAP's site tree
 * — every URL the spiders requested — and dumps one JSON object per node. */
export const SITE_TREE_DUMP_SCRIPT_FILE = 'dump-site-tree.js'
export const SITE_TREE_DUMP_OUTPUT_FILE = 'site-tree.jsonl'
export const SITE_TREE_DUMP_SCRIPT_NAME = 'sakuda-dump-site-tree'
export const SITE_TREE_DUMP_ENGINE = 'ECMAScript : Graal.js'

/** `outputPath` is the path as seen by the ZAP process (container-side when
 * ZAP runs in Docker — see `zapPath`). */
export function buildSiteTreeDumpScript(outputPath: string): string {
  return `// Generated by sakuda: dumps ZAP's site tree as JSONL for discovery.
var Model = Java.type('org.parosproxy.paros.model.Model');
var Files = Java.type('java.nio.file.Files');
var Paths = Java.type('java.nio.file.Paths');
var StandardCharsets = Java.type('java.nio.charset.StandardCharsets');
var out = [];
function walk(node) {
  var ref = node.getHistoryReference();
  if (ref) {
    out.push(JSON.stringify({
      method: String(ref.getMethod()),
      url: String(ref.getURI().toString()),
      type: ref.getHistoryType(),
      status: ref.getStatusCode()
    }));
  }
  for (var i = 0; i < node.getChildCount(); i++) walk(node.getChildAt(i));
}
walk(Model.getSingleton().getSession().getSiteTree().getRoot());
Files.write(Paths.get(${JSON.stringify(outputPath)}), out.join('\\n').getBytes(StandardCharsets.UTF_8));
print('sakuda dump-site-tree: ' + out.length + ' nodes');
`
}

const Entry = z.object({
  method: z.string(),
  url: z.string(),
  type: z.number().int(),
  status: z.number().int(),
})

export type SiteTreeEntry = z.infer<typeof Entry>

// org.parosproxy.paros.model.HistoryReference constants.
const HISTORY_TYPE_SPIDER = 2
const HISTORY_TYPE_SPIDER_AJAX = 10

export function historyTypeToSource(type: number): DiscoveredUrl['source'] {
  if (type === HISTORY_TYPE_SPIDER) return 'spider'
  if (type === HISTORY_TYPE_SPIDER_AJAX) return 'ajax'
  return 'other'
}

/** Parses the JSONL dump. Structural nodes (folders ZAP synthesizes for a
 * path prefix, never actually requested) carry status 0 and are dropped
 * here — they are not URLs anything responded to. */
export function parseSiteTreeDump(text: string): {
  entries: SiteTreeEntry[]
  structuralCount: number
  invalidLines: number
} {
  const entries: SiteTreeEntry[] = []
  let structuralCount = 0
  let invalidLines = 0
  for (const line of text.split(/\r?\n/)) {
    if (line.trim() === '') continue
    let json: unknown
    try {
      json = JSON.parse(line)
    } catch {
      invalidLines++
      continue
    }
    const r = Entry.safeParse(json)
    if (!r.success) {
      invalidLines++
      continue
    }
    if (r.data.status === 0) {
      structuralCount++
      continue
    }
    entries.push(r.data)
  }
  return { entries, structuralCount, invalidLines }
}
